name: Build, Package & Release Microformats library

on:
  release:
    types: [published]
jobs:
  build:
    name: Build Microformats library
    runs-on: ubuntu-latest
    steps:

    - name: 📄 Checkout
      uses: actions/checkout@v3

    - name: 🛠️ Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: 🛠️ Restore NuGet packages
      run: dotnet restore
      
    - name: 🚀 Build Solution
      run: dotnet build --configuration Release
      
    - name: 👟 Run tests
      run: dotnet test

    - name: 📦 Pack NuGet package
      run: dotnet pack -p VersionPrefix=${{github.event.release.tag_name}} -p ReleaseNotes="${{github.event.release.body}}" --configuration Release

    - name: 💾 Archive package
      uses: actions/upload-artifact@v3
      with:
        name: nuget-package
        path: ${{github.workspace}}/**/Microformats.*.nupkg

    - name: 💾 Archive symbols package
      uses: actions/upload-artifact@v3
      with:
        name: nuget-package
        path: ${{github.workspace}}/**/Microformats.*.snupkg

    - name: 🛠️ Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'
    
    - name: 🌐 Push NuGet package live
      run: nuget push ${{github.workspace}}/**/Microformats.*.nupkg -src https://api.nuget.org/v3/index.json
    
    - name: 🌐 Push NuGet symbol package live
      run: nuget push ${{github.workspace}}/**/Microformats.*.snupkg -src https://api.nuget.org/v3/index.json
